export const DICTIONARY = {
    DayOne: [
        {english: "to park", russian: "парковаться", id: 1, img: '/images/dayOne/topark.jpeg'},
        {english: "to give", russian: "давать", id: 2, img: '/images/dayOne/togive.jpg'},
        {english: "to live", russian: "жить", id: 3, img: '/images/dayOne/tolive.jpg'},
        {english: "to drive", russian: "водить", id: 4, img: '/images/dayOne/todrive.jpg'},
        {english: "to take", russian: "брать", id: 5, img: '/images/dayOne/totake.jpg'},
        {english: "to get on", russian: "сесть (в автобус)", id: 6, img: '/images/dayOne/togeton.jpg',},
        {english: "to get off", russian: "выйты (из автобуса)", id: 7, img: '/images/dayOne/togetoff.jpg',},
        {english: "to be late", russian: "опаздать", id: 8, img: '/images/dayOne/tobelate.jpg'},
        {english: "to run", russian: "бежать", id: 9, img: '/images/dayOne/torun.jpg'},
        {english: "to sit", russian: "сидеть", id: 10, img: '/images/dayOne/tosit.jpeg'},
    ],
    DayTwo: [
        {english: "to forget", russian: "забыть", id: 11, img: '/images/dayTwo/toforget.jpg'},
        {english: "to wait for", russian: "ждать", id: 12, img: '/images/dayTwo/towaitfor.jpg'},
        {english: "to watch", russian: "смотреть", id: 13, img: '/images/dayTwo/towatch.jpeg'},
        {english: "to cross", russian: "пересикать", id: 14, img: '/images/dayTwo/tocross.jpeg'},
        {english: "to use", russian: "использовать", id: 15, img: '/images/dayTwo/touse.jpg',},
        {english: "to keep", russian: "хранить, держать", id: 16, img: '/images/dayTwo/tokeep.jpg',},
        {english: "to look for", russian: "искать", id: 17, img: '/images/dayTwo/tolookfor.jpg',},
        {english: "to go into", russian: "зайти", id: 18, img: '/images/dayTwo/togointo.jpg'},
        {english: "to read", russian: "читать", id: 19, img: '/images/dayTwo/toread.jpeg'},
        {english: "to turn", russian: "поворачивать", id: 20, img: '/images/dayTwo/totourn.jpg',},
    ],
    DayThree: [
        {english: "to get in the car", russian: "сесть в машину", id: 11, img: '/images/dayThree/togetinthecar.jpg'},
        {english: "to go out of the car", russian: "выйти из машины", id: 12, img: '/images/dayThree/togooutofthecar.jpg'},
        {english: "to open", russian: "открыть", id: 18, img: '/images/dayThree/toopen.jpeg'},
        {english: "to write", russian: "писать", id: 13, img: '/images/dayThree/towrite.jpeg'},
        {english: "to eat", russian: "кушать", id: 14, img: '/images/dayThree/toeat.jpg'},
        {english: "to speak", russian: "говорить", id: 15, img: '/images/dayThree/tospeak.jpg',},
        {english: "to take classes", russian: "заниматься", id: 16, img: '/images/dayThree/totakecalasses.jpg',},
        {english: "to worry", russian: "беспокоиться, волноваться", id: 17, img: '/images/dayThree/toworry.jpg',},
        {english: "to understand", russian: "понимать", id: 19, img: '/images/dayThree/tounderstand.jpg'},
        {english: "to enroll", russian: "записваться", id: 20, img: '/images/dayThree/toenroll.jpg',},
    ],
    DayFour: [
        {english: "to ask for", russian: "спрашвать", id: 11, img: '/images/dayFour/toaskfor.jpg'},
        {english: "to look at", russian: "Смотреть в, на", id: 12, img: '/images/dayFour/tolookat.jpg'},
        {english: "to make", russian: "делать", id: 13, img: '/images/dayFour/tomake.jpg'},
        {english: "Bench", russian: "скамейка", id: 14, img: '/images/dayFour/bench.jpg'},
        {english: "Newspaper", russian: "газета", id: 15, img: '/images/dayFour/newspaper.jpg',},
        {english: "Signs", russian: "знаки", id: 16, img: '/images/dayFour/signs.jpg'},
        {english: "Street", russian: "улица", id: 17, img: '/images/dayFour/street.jpg'},
        {english: "Classroom", russian: "класс", id: 18, img: '/images/dayFour/classroom.jpg'},
        {english: "Welcome", russian: "добро пожаловать", id: 19, img: '/images/dayFour/wolcome.jpg'},
        {english: "U-turn", russian: "разварот", id: 20, img: '/images/dayFour/u-turn.jpg'},
    ],
    DayFive: [
        {english: "Parking lot", russian: "парковка", id: 11, img: '/images/dayFive/parkinglot.jpg'},
        {english: "Grass", russian: "трава", id: 12, img: '/images/dayFive/grass.jpg'},
        {english: "Pencil", russian: "карандаш", id: 13, img: '/images/dayFive/pencel.jpg'},
        {english: "Page", russian: "страница", id: 14, img: '/images/dayFive/page.jpg'},
        {english: "Paper", russian: "бумага", id: 15, img: '/images/dayFive/paper.jpg'},
        {english: "Quickly", russian: "быстро", id: 16, img: '/images/dayFive/quickly.jpg'},
        {english: "Lunch", russian: "обед", id: 17, img: '/images/dayFive/luch.jpg'},
        {english: "Well", russian: "хорошо", id: 18, img: '/images/dayFive/well.jpg'},
        {english: "Room", russian: "комното, место", id: 19, img: '/images/dayFive/room.jpg'},
        {english: "Map", russian: "карта", id: 20, img: '/images/dayFive/map.jpg'},
    ],
    DaySix: [
        {english: "Maybe", russian: "возможно", id: 11, img: '/images/daySix/maybe.png'},
        {english: "Direction", russian: "напровление", id: 12, img: '/images/daySix/direction.jpg'},
        {english: "Card", russian: "карточка", id: 13, img: '/images/daySix/card.jpg'},
        {english: "Instruction", russian: "инструкция", id: 14, img: '/images/daySix/instruction.jpg'},
        {english: "To be right", russian: "быть правым", id: 15, img: '/images/daySix/toberight.jpg'},
        {english: "To type", russian: "печатать", id: 16, img: '/images/daySix/totype.jpg'},
        {english: "To spell", russian: "произности по буквам", id: 17, img: '/images/daySix/tospell.jpg'},
        {english: "To need", russian: "нуждаться", id: 18, img: '/images/daySix/toneed.jpg'},
        {english: "To want", russian: "хотеть", id: 19, img: '/images/daySix/towant.jpg'},
        {english: "To make noise", russian: "шумить", id: 20, img: '/images/daySix/tomakenoise.jpg'},
    ],
    DaySeven: [
        {english: "To cook", russian: "готовить", id: 11, img: '/images/daySeven/tocook.png'},
        {english: "To smoke", russian: "курить", id: 12, img: '/images/daySeven/tosmoke.jpg'},
        {english: "To learn", russian: "учить", id: 13, img: '/images/daySeven/tolearn.jpg'},
        {english: "To study", russian: "учиться", id: 14, img: '/images/daySeven/tostudy.jpg'},
        {english: "To teach", russian: "учить, проподовать", id: 15, img: '/images/daySeven/toteach.jpg'},
        {english: "To try", russian: "пробовать, пытаться", id: 16, img: '/images/daySeven/totry.jpg'},
        {english: "To hear", russian: "слышать", id: 17, img: '/images/daySeven/tohear.jpg'},
        {english: "To be tired", russian: "уставить", id: 18, img: '/images/daySeven/tobetired.jpg'},
        {english: "To listen to", russian: "слушать", id: 20, img: '/images/daySeven/tolistento.jpg'},
    ],
    DayEight: [
        {english: "To pay", russian: "платить", id: 11, img: '/images/dayEight/topay.jpg'},
        {english: "To buy", russian: "покупать", id: 12, img: '/images/dayEight/tobuy.jpg'},
        {english: "To practice", russian: "практиковаться", id: 13, img: '/images/dayEight/topractice.jpg'},
        {english: "To find", russian: "найти", id: 14, img: '/images/dayEight/tofind.jpeg'},
        {english: "To sleep", russian: "спать", id: 15, img: '/images/dayEight/tosleep.jpg'},
        {english: "To carry", russian: "носить", id: 16, img: '/images/dayEight/tocarry.jpg'},
        {english: "To move", russian: "переезжать", id: 17, img: '/images/dayEight/tomove.jpg'},
        {english: "To get up", russian: "вставать", id: 18, img: '/images/dayEight/togetup.jpg'},
        {english: "To come over", russian: "навещать", id: 19, img: '/images/dayEight/tocomeover.jpg'},
        {english: "Skills", russian: "навыки, умения", id: 20, img: '/images/dayEight/skills.jpg'},
    ],
};
