
export const DICTIONARY = {
  DayOne: [
    {english: "to park", russian: "парковаться", id: 1, img: '/images/dayOne/topark.jpeg'},
    { english: "to give", russian: "давать", id: 2, img: '/images/dayOne/togive.jpg' },
    { english: "to live", russian: "жить", id: 3, img: '/images/dayOne/tolive.jpg' },
    { english: "to drive", russian: "водить", id: 4, img: '/images/dayOne/todrive.jpg' },
    { english: "to take", russian: "брать", id: 5, img: '/images/dayOne/totake.jpg' },
    {english: "to get on", russian: "сесть (в автобус)", id: 6, img: '/images/dayOne/togeton.jpg',},
    {english: "to get off", russian: "выйты (из автобуса)", id: 7, img: '/images/dayOne/togetoff.jpg',},
    {english: "to be late", russian: "опаздать", id: 8, img: '/images/dayOne/tobelate.jpg'},
    { english: "to run", russian: "бежать", id: 9, img: '/images/dayOne/torun.jpg' },
    { english: "to sit", russian: "сидеть", id: 10, img: '/images/dayOne/tosit.jpg' },
  ],
  DayTwo: [
    { english: "to forget", russian: "забыть", id: 11, img: '/images/dayTwo/toforget.jpg' },
    { english: "to wait for", russian: "ждать", id: 12, img: '/images/dayTwo/towaitfor.jpg' },
    { english: "to watch", russian: "смотреть", id: 13, img: '/images/dayTwo/towatch.jpeg' },
    {english: "to cross", russian: "пересикать", id: 14, img: '/images/dayTwo/tocross.jpeg'},
    {english: "to use", russian: "использовать", id: 15, img: '/images/dayTwo/touse.jpg',},
    {english: "to keep", russian: "хранить, держать", id: 16, img: '/images/dayTwo/tokeep.jpg',},
    {english: "to look for", russian: "искать", id: 17, img: '/images/dayTwo/tolookfor.jpg',},
    { english: "to go into", russian: "зайти", id: 18, img: '/images/dayTwo/togointo.jpg' },
    { english: "to read", russian: "читать", id: 19, img: '/images/dayTwo/toread.jpeg' },
    {english: "to turn", russian: "поворачивать", id: 20, img: '/images/dayTwo/totourn.jpg',},
  ],
  DayThree: [
    { english: "to forget", russian: "забыть", id: 11, img: '/images/dayTwo/toforget.jpg' },
    { english: "to wait for", russian: "ждать", id: 12, img: '/images/dayTwo/towaitfor.jpg' },
    { english: "to watch", russian: "смотреть", id: 13, img: '/images/dayTwo/towatch.jpeg' },
    {english: "to cross", russian: "пересикать", id: 14, img: '/images/dayTwo/tocross.jpeg'},
    {english: "to use", russian: "использовать", id: 15, img: '/images/dayTwo/touse.jpg',},
    {english: "to keep", russian: "хранить, держать", id: 16, img: '/images/dayTwo/tokeep.jpg',},
    {english: "to look for", russian: "искать", id: 17, img: '/images/dayTwo/tolookfor.jpg',},
    { english: "to go into", russian: "зайти", id: 18, img: '/images/dayTwo/togointo.jpg' },
    { english: "to read", russian: "читать", id: 19, img: '/images/dayTwo/toread.jpeg' },
    {english: "to turn", russian: "поворачивать", id: 20, img: '/images/dayTwo/totourn.jpg',},
  ],
  DayFour: [
    { english: "to forget", russian: "забыть", id: 11, img: '/images/dayTwo/toforget.jpg' },
    { english: "to wait for", russian: "ждать", id: 12, img: '/images/dayTwo/towaitfor.jpg' },
    { english: "to watch", russian: "смотреть", id: 13, img: '/images/dayTwo/towatch.jpeg' },
    {english: "to cross", russian: "пересикать", id: 14, img: '/images/dayTwo/tocross.jpeg'},
    {english: "to use", russian: "использовать", id: 15, img: '/images/dayTwo/touse.jpg',},
    {english: "to keep", russian: "хранить, держать", id: 16, img: '/images/dayTwo/tokeep.jpg',},
    {english: "to look for", russian: "искать", id: 17, img: '/images/dayTwo/tolookfor.jpg',},
    { english: "to go into", russian: "зайти", id: 18, img: '/images/dayTwo/togointo.jpg' },
    { english: "to read", russian: "читать", id: 19, img: '/images/dayTwo/toread.jpeg' },
    {english: "to turn", russian: "поворачивать", id: 20, img: '/images/dayTwo/totourn.jpg',},
  ],
  DayFive: [
    { english: "to forget", russian: "забыть", id: 11, img: '/images/dayTwo/toforget.jpg' },
    { english: "to wait for", russian: "ждать", id: 12, img: '/images/dayTwo/towaitfor.jpg' },
    { english: "to watch", russian: "смотреть", id: 13, img: '/images/dayTwo/towatch.jpeg' },
    {english: "to cross", russian: "пересикать", id: 14, img: '/images/dayTwo/tocross.jpeg'},
    {english: "to use", russian: "использовать", id: 15, img: '/images/dayTwo/touse.jpg',},
    {english: "to keep", russian: "хранить, держать", id: 16, img: '/images/dayTwo/tokeep.jpg',},
    {english: "to look for", russian: "искать", id: 17, img: '/images/dayTwo/tolookfor.jpg',},
    { english: "to go into", russian: "зайти", id: 18, img: '/images/dayTwo/togointo.jpg' },
    { english: "to read", russian: "читать", id: 19, img: '/images/dayTwo/toread.jpeg' },
    {english: "to turn", russian: "поворачивать", id: 20, img: '/images/dayTwo/totourn.jpg',},
  ],
  DaySix: [
    { english: "to forget", russian: "забыть", id: 11, img: '/images/dayTwo/toforget.jpg' },
    { english: "to wait for", russian: "ждать", id: 12, img: '/images/dayTwo/towaitfor.jpg' },
    { english: "to watch", russian: "смотреть", id: 13, img: '/images/dayTwo/towatch.jpeg' },
    {english: "to cross", russian: "пересикать", id: 14, img: '/images/dayTwo/tocross.jpeg'},
    {english: "to use", russian: "использовать", id: 15, img: '/images/dayTwo/touse.jpg',},
    {english: "to keep", russian: "хранить, держать", id: 16, img: '/images/dayTwo/tokeep.jpg',},
    {english: "to look for", russian: "искать", id: 17, img: '/images/dayTwo/tolookfor.jpg',},
    { english: "to go into", russian: "зайти", id: 18, img: '/images/dayTwo/togointo.jpg' },
    { english: "to read", russian: "читать", id: 19, img: '/images/dayTwo/toread.jpeg' },
    {english: "to turn", russian: "поворачивать", id: 20, img: '/images/dayTwo/totourn.jpg',},
  ],
  DaySeven: [
    { english: "to forget", russian: "забыть", id: 11, img: '/images/dayTwo/toforget.jpg' },
    { english: "to wait for", russian: "ждать", id: 12, img: '/images/dayTwo/towaitfor.jpg' },
    { english: "to watch", russian: "смотреть", id: 13, img: '/images/dayTwo/towatch.jpeg' },
    {english: "to cross", russian: "пересикать", id: 14, img: '/images/dayTwo/tocross.jpeg'},
    {english: "to use", russian: "использовать", id: 15, img: '/images/dayTwo/touse.jpg',},
    {english: "to keep", russian: "хранить, держать", id: 16, img: '/images/dayTwo/tokeep.jpg',},
    {english: "to look for", russian: "искать", id: 17, img: '/images/dayTwo/tolookfor.jpg',},
    { english: "to go into", russian: "зайти", id: 18, img: '/images/dayTwo/togointo.jpg' },
    { english: "to read", russian: "читать", id: 19, img: '/images/dayTwo/toread.jpeg' },
    {english: "to turn", russian: "поворачивать", id: 20, img: '/images/dayTwo/totourn.jpg',},
  ],
  DayEight: [
    { english: "to forget", russian: "забыть", id: 11, img: '/images/dayTwo/toforget.jpg' },
    { english: "to wait for", russian: "ждать", id: 12, img: '/images/dayTwo/towaitfor.jpg' },
    { english: "to watch", russian: "смотреть", id: 13, img: '/images/dayTwo/towatch.jpeg' },
    {english: "to cross", russian: "пересикать", id: 14, img: '/images/dayTwo/tocross.jpeg'},
    {english: "to use", russian: "использовать", id: 15, img: '/images/dayTwo/touse.jpg',},
    {english: "to keep", russian: "хранить, держать", id: 16, img: '/images/dayTwo/tokeep.jpg',},
    {english: "to look for", russian: "искать", id: 17, img: '/images/dayTwo/tolookfor.jpg',},
    { english: "to go into", russian: "зайти", id: 18, img: '/images/dayTwo/togointo.jpg' },
    { english: "to read", russian: "читать", id: 19, img: '/images/dayTwo/toread.jpeg' },
    {english: "to turn", russian: "поворачивать", id: 20, img: '/images/dayTwo/totourn.jpg',},
  ],
};
